<?php return array (
  'keys' => 
  array (
    0 => 'site.title',
    1 => 'site.meta',
    2 => 'index.title',
    3 => 'index.short-description',
    4 => 'index.about-title',
    5 => 'index.about-description',
    6 => 'site.copy',
    7 => 'site.terms',
    8 => 'site.policy',
    9 => 'site.cookies',
    10 => 'index.description-title1',
    11 => 'index.description-title2',
    12 => 'index.description-title3',
    13 => 'index.description-title4',
    14 => 'index.description-text1',
    15 => 'index.description-text2',
    16 => 'index.description-text3',
    17 => 'index.description-text4',
    18 => 'contact.address',
    19 => 'about-us.title',
    20 => 'about-us.description',
    21 => 'about-us.description2',
    22 => 'about-us.offer-title1',
    23 => 'about-us.offer-title2',
    24 => 'about-us.offer-title3',
    25 => 'about-us.offer-title4',
    26 => 'about-us.offer-title6',
    27 => 'about-us.offer-description1',
    28 => 'about-us.offer-description2',
    29 => 'about-us.offer-description3',
    30 => 'about-us.offer-description4',
    31 => 'about-us.offer-description6',
    32 => 'about-us.offer-description5',
    33 => 'about-us.offer-title5',
    34 => 'about-us.offer5-title',
    35 => 'about-us.offer5-description',
    36 => 'about-us.offer6-description',
    37 => 'about-us.offer6-title',
    38 => 'fleet.description',
    39 => 'flights.description',
    40 => 'flights.tours',
    41 => 'site.booking-page',
    42 => 'site.booking-thank',
  ),
);